<a href="https://colab.research.google.com/github/sandeeprairai/python-/blob/main/py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
first_numpy_array=np.array([1,2,3,4])
first_numpy_array

array([1, 2, 3, 4])

In [4]:
#array with zeros
array_with_zeros=np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
#array with ones
array_with_ones=np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
#array with empty
array_with_empty=np.empty((2,3))
array_with_empty

array([[1.799376e-316, 0.000000e+000, 0.000000e+000],
       [0.000000e+000, 0.000000e+000, 0.000000e+000]])

In [7]:
#array with arrange method
np_arange=np.arange(12)
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
#reshape the array
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
#Linespace for linearly(equal) spaced data elements
np_linspace=np.linspace(1,6,5)
np_linspace

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [11]:
#One dimensional array
oneD_array=np.arange(15)
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
#Two Dimensional Array
TwoD_array=oneD_array.reshape(3,5)
TwoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
ThreeD_array=np.arange(27).reshape(3,3,3)
ThreeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [15]:
#Pandas Library
#1-Series
import pandas as pd
import numpy as np
first_series=pd.Series(list('abcdef'))
first_series

0    a
1    b
2    c
3    d
4    e
5    f
dtype: object

In [17]:
#Creating Series from ndarray
np_country=np.array(['A','B','C','D','E','F','G','H','I','J','K'])
s_country=pd.Series(np_country)
s_country

0     A
1     B
2     C
3     D
4     E
5     F
6     G
7     H
8     I
9     J
10    K
dtype: object

In [18]:
#creating Series with dict data
dict_country_gdp=pd.Series([10,12,23,45,36,78,89,90,85,64],index=['A','B','C','D','E','F','G','H','I','J'])
dict_country_gdp

A    10
B    12
C    23
D    45
E    36
F    78
G    89
H    90
I    85
J    64
dtype: int64

In [19]:
#Print Series with scalar 
scalar_seies=pd.Series(5,index=['a','b','c','d','e'])
scalar_seies

a    5
b    5
c    5
d    5
e    5
dtype: int64

In [24]:
dict_country_gdp[0]
dict_country_gdp[0:5]
dict_country_gdp.loc['C']
dict_country_gdp[0]

10

In [25]:
first_vector_series=pd.Series([1,2,3,4],index=['a','b','c','d'])
second_vector_series=pd.Series([10,20,30,40],index=['a','b','c','d'])
first_vector_series+second_vector_series

a    11
b    22
c    33
d    44
dtype: int64